# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RSSReaderApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RSSReaderApp
pod 'LineSDKSwift', '~> 5.0'

  target 'RSSReaderAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSSReaderAppUITests' do
    # Pods for testing
  end

end
